version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-app-build-dependencies-{{ checksum "settings.gradle.kts" }}-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle.properties" }}

      - run:
          name: DL all dependencies
          command: ./gradlew resolveDependencies

      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: v1-app-build-dependencies-{{ checksum "settings.gradle.kts" }}-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle.properties" }}

  beta:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-app-build-dependencies-{{ checksum "settings.gradle.kts" }}-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle.properties" }}

      - run:
          name: DL all dependencies
          command: ./gradlew resolveDependencies

      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: v1-app-build-dependencies-{{ checksum "settings.gradle.kts" }}-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle.properties" }}

      - run:
          name: Release
          command: echo ${CIRCLE_TAG#beta-}

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test:
          filters:
            tags:
              only: /.*/
      - beta:
          requires:
            - build_and_test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^beta-.*/