name: CI-beta

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: v1-gradle-caches-${{ hashFiles('settings.gradle.kts') }}-${{ hashFiles('build.gradle.kts') }}-${{ hashFiles('gradle.properties') }}
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: v1-gradle-caches-${{ hashFiles('settings.gradle.kts') }}-${{ hashFiles('build.gradle.kts') }}-${{ hashFiles('gradle.properties') }}
    - name: DL all dependencies
      run: ./gradlew resolveDependencies
    - name: Tests
      run: ./gradlew test

  beta-release:
    needs: build
    runs-on: ubuntu-latest
    if: startswith(github.ref, 'tags/beta-')
    steps:
    - name: get the version
      id: get_version
      run: echo ::set-output name=version::${github_ref/refs\/tags\//}
    - name: release
      run: ./gradlew appversion -dversion=${version#beta-}
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'tags/release-')
    steps:
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Release
      run: ./gradlew appVersion -DVERSION=${VERSION#release-}
